// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // Point directly to the actual schema file name
  schema: "src/models", 
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Forcefully inject the URL from your environment variables
    url: process.env.DATABASE_URL,
  },
});

